apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-server-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server-container
          image: devopscode44/nginx-assignment1-docker-k8s:v1
          ports:
            - containerPort: 80
